### PR TITLE
Add basic API for Directions

### PR DESCRIPTION
**Pull request by xoolive**
Please find enclosed a basic API for plotting itineraries. 

capture du 2016-06-21 10-12-46

### CODE REVIEW

**Comment by xoolive** [comment]
As I am a Javascript illiterate, the PR is revamped copy-paste from this post:
https://stackoverflow.com/questions/3404499/plotting-a-route-on-google-maps

**Comment by pbugnion** [comment]
This is great! Thanks very much for contributing.

I'll review this over the next couple of days and get back to you.

**Comment by pbugnion** [comment]
This is great. 

I have a couple of suggestions for the `DirectionsView` (in the JavaScript part of the code). The two main issues are:

 - the implementation currently overwrites the model's data array when it extracts the last point and the waypoints. When you write `var data = this.model.get("data")`, this just copies a reference, not the array itself. The changes are not apparent until someone calls `this.touch()` on the view, which propagates the model changes back to Python. At that point, the Python layer tries to calculate bounds and everything breaks. 
 - raising an alert is probably not the best way to handle exceptions: it would be better to throw an exception in the Python layer. This is annoyingly tricky to do because the error happens in the front-end, and we need to somehow propagate it back to the Python kernel. There may be a simpler way to do this, but I suggest setting a flag called `layer_status` in the model and updating that flag from the view when the response comes in. The Python model can then observe that flag and raise an exception.

I've written a bit of code to illustrate those points:

```javascript
var DirectionsLayerView = GMapsLayerView.extend({
    render: function() {
        var that = this ;

        var rendererOptions = { map:this.map_view.map };

        that.directionsDisplay=new google.maps.DirectionsRenderer(rendererOptions);

        var model_data = this.model.get("data");
        var orig = that.get_orig(model_data);
        var dest = that.get_dest(model_data);
        var waypoints = that.get_wps(model_data);

        var request= {
            origin: orig,
            destination: dest,
            waypoints: waypoints,
            travelMode: google.maps.DirectionsTravelMode.DRIVING
        };

        var direction_service = new google.maps.DirectionsService();

        direction_service.route(request, function(response,status) {
           // print to the browser console (mostly for debugging) 
           console.log("Directon service returned: ", status) ; 
           // set a flag in the model
            that.model.set("layer_status", status) ; 
            that.touch() ; // push `layer_status` changes to the model
            if (status == google.maps.DirectionsStatus.OK) {
                that.response = that.directionsDisplay
                that.directionsDisplay.setDirections(response);
            }
        });
    },


    add_to_map_view: function(map_view) {},

    get_orig: function(model_data) {
        var first_point = _.first(model_data);
        return new google.maps.LatLng(first_point[0], first_point[1]);
    },

    get_dest: function(model_data) {
        var last_point = _.last(model_data); 
        return new google.maps.LatLng(last_point[0], last_point[1]);
    },

    get_wps: function(model_data) {
        var without_first = _.tail(model_data);
        var without_last = _.initial(without_first) ;
        var data_as_google = _.map(without_last, function(point) {
            var google_point = new google.maps.LatLng(point[0], point[1]);
            return google_point;
        });
        return data_as_google;
    }

});
```

... and in Python:

```python
class DirectionServiceException(Exception):
    pass
```

```python
class Directions(widgets.Widget):
   ...
   layer_status = CUnicode().tag(sync=True) // flag that is updated by the view.

    @observe("layer_status")
    def _handle_layer_status(self, change):
        print(change["new"])
        if change["new"] != "OK":
            raise DirectionServiceException("No directions for this data.")
```

**Comment by xoolive** [comment]
Thank you so much. I will merge this in and comment a ton tomorrow!

**Comment by xoolive** [comment]
Thank you again for the advice, esp. about the alert as I had no idea how to propagate the exception back to Python! I merged your recommendations (and debugged...).

Note that:
- The error returned by Google API is not passed as print but as a parameter of the exception.
- I added an assert on the length of data to avoid itineraries between one point

I think it is mergeable as is for now. (Enough for my needs...)

Still, there is some room for improvements, here are some reflections:
- It would be great to be able to pass as data either lat/lon tuples or the kind of dictionaries returned by [googlemaps](https://github.com/googlemaps/google-maps-services-python) API. 
```python
import googlemaps
import gmaps

client = googlemaps.Client(">>>> fill in your API key <<<<")
location = client.geocode("Toulouse")
print (location) # have a look!
gmaps.add_layer(Directions(data=[client.geocode("Toulouse"), client.geocode("Paris")]))
```

- Also, we hardcoded the travelmode parameter which could be passed as parameter (though I have no idea how to pass something more than `data`). More generally, it would be great to have a close interface to `googlemaps` and write:
```python
# from googlemaps documentation
directions_result = client.directions("Sydney Town Hall",
                                     "Parramatta, NSW",
                                     mode="transit",
                                     departure_time=now)
# how about this ?
gmaps.add_layer(Directions("Sydney Town Hall",
                           "Parramatta, NSW",
                           mode="transit",
                           departure_time=now))
```

For future references, there is a good overview of the interface [here](https://github.com/googlemaps/google-maps-services-python/blob/master/test/test_directions.py).

**Comment by pbugnion** [comment]
This is really good. Thanks for all this work!

I have one last suggestion before merging this. We probably shouldn't use an assertion to verify that the user enters at least two points. Assertions are normally reserved for verifying contracts *internal to the program*, not for things that could fail because of user error. In 'normal' Python packages, you would probably raise a `ValueError`, but here, the [traitlets](http://traitlets.readthedocs.io/en/stable/index.html) machinery that underpins widgets lets us do this more elegantly. In the definition of the `data` trait, you can specify a minimum length on the list:

```python
class Directions(widgets.Widget):
    ...
    data = List(minlen=2).tag(sync=True)
```

This then throws a `TraitError` if the user tries to enter the wrong data, or fails to specify a data array:

```python
d = Directions(data=[[48.0, 5.0]])
---------------------------------------------------------------------------
TraitError                                Traceback (most recent call last)
...
TraitError: The 'data' trait of a Directions instance must be of length 2 <= L <= 9223372036854775807, but a value of [[50.0, 4.0]] was specified.
```

**Comment by pbugnion** [comment]
I will open another issue with suggestions on for passing other parameters to the JavaScript layer.

**Comment by xoolive** [comment]
Done. I rebased everything into a single commit onto `master`.

**Comment by pbugnion** [comment]
Great! Merging this now. There is definitely no need to squash commits into one in the future.

**Comment by xoolive** [comment]
Ok thank you. I am just extra cautious, there are some git nazis out there...

**Pull request merged**
