### PR TITLE
Updated such that it runs with iPython 4 and Jupyter

### PR DESCRIPTION
**Pull request by fwahl711**
Hey Pascal,

first of all, thanks for the great code! I tried to run it today on a ipython 4 installation where notebook is now split into jupyter and also some imports have changed. After a few hours of tinkering (no prior JS experience at all) my colleague and I got it to work. Maybe it's worth it for you to merge...[never did this before, first time i was "fixing" someone elses code here...I hope this is the right way]

All the best,
Florian

### CODE REVIEW

**Comment by pbugnion** [comment]
Oh wow -- Thanks a lot for your hard work. Will give this a whirl tonight, but very happy to merge asap.

**Comment by pbugnion** [comment]
I've had a play with this and it looks fine. 

My main concern is that this breaks backwards compatibility with IPython 2 and 3, which are still in (very) widespread use, as far as I know -- I can't find dates on the Jupyter/IPython split and the release of IPython 4, but IPython 3 was only released in February 2015, so it's still all pretty new.

That said, I think it makes sense for the bleeding edge of a repo to work with the latest version of the libraries it depends on. I'll merge this and rename the previous master branch to `ipy23` so that both are accessible. I won't make a release on Pypi until we've at least got IPython 3 support in master.

Thanks a lot for your hard work doing this -- adding IPython 4 support was on my list of things to do.

**Comment by fwahl711** [comment]
Hey Pascal,

thanks for the fast merge! First time I tried this, feels good ;)
Thanks you fro the hard work of making it in the first place and putting it
online!

All the best,
Florian

**Comment by pbugnion** [comment]
Congratulations on your first PR! Open source is all about the community!

**Pull request merged**
